title: Portfolio
description: My portfolio resume
author: Sarah

# Theme (optional)
remote_theme: daattali/beautiful-jekyll

# URL settings
baseurl: ""  # Leave empty if using username.github.io
url: "https://sarahnpadilla.github.io"

# Build settings
plugins:
  - jekyll-remote-theme
markdown: kramdown
